name: 'template-transformer-and-cleanup'
author: 'thynclabs'
description: 'ztodo'

inputs:
  text:
    description: 'Text to replace'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  args:
    - ${{ inputs.text }}
branding:
  icon: terminal
  color: green
