name: 'Replace and Delete Action'
description: 'Replace a keyword in all files and delete .github folder'

inputs:
  text-to-replace:
    description: 'New repository name to replace "my-template"'
    required: true

runs:
  using: 'bash'
  main: './action.sh ${{github.repository}}'
