name: template-transformer-and-cleanup
description: Adds a file (abc.txt) and commits it to the repository

inputs:
  github-token:
    description: 'GitHub Token'
    required: false

runs:
  using: 'composhttps://github.com/thynclabs/template-transformer-and-cleanup/tree/mainite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create abc.txt file
      run: echo "Hello, World!" > abc.txt

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add abc.txt
        git commit -m "Add abc.txt via GitHub Action"
        git push
