name: 'Template Cleanup Action'
description: 'Replace the template repository name in all files with a new value, and push the changes to the branch.'
author: 'Thync Labs'
branding:
  icon: terminal
  color: green
inputs:
  search-keyword:
    description: 'The string to replace in all files'
    required: true
  replace-keyword:
    description: 'The string to replace the search-keyword with'
    required: true
  github_url:
    description: 'GitHub url or GitHub Enterprise url'
    required: false
    default: ${{ github.server_url }}
  workflow_token:
    description: 'PAT token with workflow permissions'
    required: true
  repository:
    description: 'Repository name'
    required: true
    default: ${{ github.repository }}
  branch:
    description: 'Destination branch to push changes'
    required: false
    default: ${{ github.ref }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_SEARCH-KEYWORD: ${{ inputs.search-keyword }}
    INPUT_REPLACE-KEYWORD: ${{ inputs.replace-keyword }}
    INPUT_GITHUB_URL: ${{ inputs.github_url }}
    INPUT_WORKFLOW_TOKEN: ${{ inputs.workflow_token }}
    INPUT_REPOSITORY: ${{ inputs.repository }}
    INPUT_BRANCH: ${{ inputs.branch }}
#  args:
#    - ${{ inputs.search-keyword }}
#    - ${{ inputs.replace-keyword }}
#    - ${{ inputs.github_url }}
#    - ${{ inputs.workflow_token }}
#    - ${{ inputs.repository }}
#    - ${{ inputs.branch }}
